In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [1]:
import cv2 as c

In [2]:
im=c.imread('photo')
c.imshow('op',im)
c.waitKey(0)
c.destroyAllWindows()
print(im)

[[[ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 [[ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 [[ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 ...

 [[248 237 226]
  [248 237 226]
  [247 236 225]
  ...
  [250 239 227]
  [247 236 224]
  [249 238 226]]

 [[247 236 225]
  [246 235 224]
  [248 237 226]
  ...
  [249 238 226]
  [248 237 225]
  [248 237 225]]

 [[249 238 227]
  [247 236 225]
  [249 238 227]
  ...
  [247 236 224]
  [248 237 225]
  [248 237 225]]]


In [7]:
import cv2

video_capture = cv2.VideoCapture(0)

while True:
    # Read frame from the webcam
    ret, frame = video_capture.read()

    # Display the frame
    cv2.imshow('Webcam', frame)

    # Exit loop if 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture object and close windows
video_capture.release()
cv2.destroyAllWindows('Webcam')

SystemError: <built-in function destroyAllWindows> returned NULL without setting an exception

In [1]:
pip install flask

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install socket

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement socket (from versions: none)
ERROR: No matching distribution found for socket


In [ ]:
import cv2
import requests
import numpy as np

url = 'http://192.168.1.6:8000/video_feed'

while True:
    try:
        # Make a GET request to the server
        response = requests.get(url)

        # Convert the received bytes to a NumPy array
        img_array = np.array(bytearray(response.content), dtype=np.uint8)

        # Decode the array to an OpenCV image
        frame = cv2.imdecode(img_array, 1)

        # Display the frame
        cv2.imshow('Mobile Camera', frame)

        if cv2.waitKey(1) == ord('q'):
            break

    except requests.exceptions.RequestException as e:
        print(e)
        break

cv2.destroyAllWindows()


In [4]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [ ]:
conFile='ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'


In [3]:
import cv2 as c
im=c.imread('photo',-1)
c.imshow('op',im)
c.waitKey(0)
c.destroyAllWindows()

In [4]:
import cv2 as c
im=c.imread('photo',0)
c.imshow('op',im)
c.waitKey(0)
c.destroyAllWindows()

In [2]:
import cv2 as c
im=c.imread('photo',1)
c.imshow('op',im)
c.waitKey(0)
c.destroyAllWindows()

In [1]:
import cv2 as c
im=c.imread('photo',10000)
c.imshow('op',im)
c.waitKey(0)
c.destroyAllWindows()

In [2]:
import cv2 as c
im=c.imread('photo',1)
#c.imshow('op',im)
c.imwrite('o.jpg',im)
c.waitKey(0)
c.destroyAllWindows()

# resizing

In [1]:
import cv2 as c
im=c.imread('photo',1)
dim=(250,300)
re=c.resize(im,dim)
c.imshow('op',re)
c.waitKey(0)
c.destroyAllWindows()

In [2]:
import cv2 as c
im=c.imread('photo',1)
print('op',im.shape)


op (1080, 1920, 3)


In [3]:
import cv2 as c
im=c.imread('photo',1)
w=im.shape[1]
h=300
dim=(w,h)
re=c.resize(im,dim)
c.imshow('op',re)
c.waitKey(0)
c.destroyAllWindows()

In [7]:
import cv2 as c
im=c.imread('photo',1)
w=im.shape[0]
h=im.shape[1]
dim=(h,w)
re=c.resize(im,dim)
c.imshow('op',re)
c.waitKey(0)
c.destroyAllWindows()

# Morphological operation

In [ ]:
import cv2 as c
import numpy as np
im=c.imread('photo')

kernel=np.onces((5,5),dtype='uint8')

In [1]:
#Capturing Video from a Webcam:

import cv2

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()

    # Check if the frame is empty or has invalid dimensions
    if not ret or frame.size == 0:
        continue

    cv2.imshow('Video', frame)

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'filter2D'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'


In [2]:
import cv2
import urllib.request
import numpy as np

url = "http://192.168.1.3:8080/video"
while True:
    # Read the frame from the mobile camera
    stream = urllib.request.urlopen(url)
    img_np = np.array(bytearray(stream.read()), dtype=np.uint8)
    frame = cv2.imdecode(img_np, -1)

    # Display the frame
    cv2.imshow("Mobile Camera", frame)

    # Exit loop if 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cv2.destroyAllWindows()        

URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

In [6]:
import cv2
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Step 1: Load the training images
image_paths = ['11.jpg', '12.jpg', '13.jpg']
images = []
for path in image_paths:
    img = cv2.imread(path, 0)  # Read the image as grayscale
    if img is not None:
        img_resized = cv2.resize(img, (50, 50))  # Resize the image to 50x50 pixels
        images.append(img_resized)
    else:
        print(f"Failed to load image: {path}")

if len(images) == 0:
    print("No valid images found. Exiting...")
    exit()

# Step 2: Perform face recognition training
X = np.array([img.flatten() for img in images])  # Flatten the images into 1D arrays
scaler = StandardScaler()  # Standardize the data
X = scaler.fit_transform(X)
pca = PCA(n_components=0.95)  # Retain 95% of the variance
X_pca = pca.fit_transform(X)

# Step 3: Initialize the webcam
cap = cv2.VideoCapture(0)

while True:
    # Step 4: Read a frame from the webcam
    ret, frame = cap.read()
    
    # Step 5: Preprocess the frame (convert to grayscale and resize)
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    frame_resized = cv2.resize(frame_gray, (50, 50))
    
    # Step 6: Flatten and scale the preprocessed frame
    frame_flattened = frame_resized.flatten()
    frame_scaled = scaler.transform([frame_flattened])
    
    # Step 7: Perform dimensionality reduction on the frame
    frame_pca = pca.transform(frame_scaled)
    
    # Step 8: Calculate Euclidean distances between the frame and training images
    distances = np.linalg.norm(X_pca - frame_pca, axis=1)
    
    # Step 9: Find the index of the closest matching image
    min_distance_idx = np.argmin(distances)
    closest_image_path = image_paths[min_distance_idx]
    
    # Step 10: Display the closest matching image
    closest_image = cv2.imread(closest_image_path)
    cv2.imshow('Closest Match', closest_image)
    
    # Step 11: Display the original frame
    cv2.imshow('Webcam', frame)
    
    # Step 12: Check for 'q' key press to exit the loop
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Step 13: Release the webcam and close windows
cap.release()
cv2.destroyAllWindows()


In [1]:
 pip install cvlib

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import cv2
import matplotlib.pyplot as plt
import cvlib as cv
import urllib.request
import numpy as np
from cvlib.object_detection import draw_bbox
import concurrent.futures
 
url='http://192.168.10.162/cam-hi.jpg'
im=None
 
def run1():
    cv2.namedWindow("live transmission", cv2.WINDOW_AUTOSIZE)
    while True:
        img_resp=urllib.request.urlopen(url)
        imgnp=np.array(bytearray(img_resp.read()),dtype=np.uint8)
        im = cv2.imdecode(imgnp,-1)
 
        cv2.imshow('live transmission',im)
        key=cv2.waitKey(5)
        if key==ord('q'):
            break
            
    cv2.destroyAllWindows()
        
def run2():
    cv2.namedWindow("detection", cv2.WINDOW_AUTOSIZE)
    while True:
        img_resp=urllib.request.urlopen(url)
        imgnp=np.array(bytearray(img_resp.read()),dtype=np.uint8)
        im = cv2.imdecode(imgnp,-1)
 
        bbox, label, conf = cv.detect_common_objects(im)
        im = draw_bbox(im, bbox, label, conf)
 
        cv2.imshow('detection',im)
        key=cv2.waitKey(5)
        if key==ord('q'):
            break
            
    cv2.destroyAllWindows()
 
 
 
if __name__ == '__main__':
    print("started")
    with concurrent.futures.ProcessPoolExecutor() as executer:
            f1= executer.submit(run1)
            f2= executer.submit(run2)

In [2]:
import cv2
import matplotlib.pyplot as plt
import cvlib as cv
import urllib.request
import numpy as np
from cvlib.object_detection import draw_bbox
import concurrent.futures
 

cap = cv2.VideoCapture(0)

im=None
 
def run1():
    cv2.namedWindow("live transmission", cv2.WINDOW_AUTOSIZE)
    while True:
        img_resp=cap.read()
        imgnp=np.array(bytearray(img_resp.read()),dtype=np.uint8)
        im = cv2.imdecode(imgnp,-1)
 
        cv2.imshow('live transmission',im)
        key=cv2.waitKey(5)
        if key==ord('q'):
            break
            
    cv2.destroyAllWindows()
        
def run2():
    cv2.namedWindow("detection", cv2.WINDOW_AUTOSIZE)
    while True:
        img_resp=urllib.request.urlopen(url)
        imgnp=np.array(bytearray(img_resp.read()),dtype=np.uint8)
        im = cv2.imdecode(imgnp,-1)
 
        bbox, label, conf = cv.detect_common_objects(im)
        im = draw_bbox(im, bbox, label, conf)
 
        cv2.imshow('detection',im)
        key=cv2.waitKey(5)
        if key==ord('q'):
            break
            
    cv2.destroyAllWindows()
 
 
 
if __name__ == '__main__':
    print("started")
    with concurrent.futures.ProcessPoolExecutor() as executer:
            f1= executer.submit(run1)
            f2= executer.submit(run2)

started


In [3]:
pip install pyseries


     ---------------------------------------- 2.2/2.2 MB 989.3 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 14.1/14.1 MB 1.1 MB/s eta 0:00:00
  Created wheel for sklearn: filename=sklearn-0.0.post5-py3-none-any.whl size=2970 sha256=f43f35444ae000f0770cedfa1e9ae468c3b8d9e65459a76dcc739d9b4a08a418
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\5c\47\e1\386fa7740f1947ad87d16c68041c16ad8c23ca2bfd139a3fe5
Successfully built sklearn


In [1]:
pip install pyserial

     ---------------------------------------- 90.6/90.6 kB 2.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.
